a bit improvement - compare the new file via cmp and shows the status. - check the existence of the file before comparing.

diff --git a/alsa/utils/module-options b/alsa/utils/module-options
--- a/alsa/utils/module-options
+++ b/alsa/utils/module-options
@@ -6,6 +6,19 @@ else
   file=$1
 fi
 
+if [ ! -f $file ]; then
+    echo "file $file not found"
+    exit 1
+fi
+
+rm -f $file.new
 sed -e 's/snd_//g' < $file > $file.new
-diff -u $file $file.new | less
-echo "Please, check and copy $file.new to $file"
+if cmp -s $file $file.new; then
+    # nothing changed
+    rm -f $file.new
+    echo "Nothing to be changed."
+else
+    diff -u $file $file.new | less
+    echo "Please, check and copy $file.new to $file"
+fi
+exit 0
